Chinese Remainder Theorem added
sanscript-tech/hacking-tools-scripts pull request #154
Opened 2020-10-25 17:05 UTC by Mukulbaid63

### Your checklist for this pull request
:warning: Please review the [guidelines for contributing](https://github.com/sanscript-tech/hacking-tools-scripts/blob/main/CONTRIBUTING.md) to this repository.

Parent issue: #33 

### Type of change

**Select all that applies**:
* [✔️ ] New feature (non-breaking change which adds functionality)
* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

### Checklist:

* [ ] My code follows the style guidelines(Clean Code) of this project.
* [ ] I have performed a self-review of my own code.
* [ ] I have used consistent code conventions and clear function/method/variable names.
* [ ] I have commented on my code, particularly in hard-to-understand areas.
* [ ] I have created a helpful and easy to understand README.md which contains description, requirements and use case.
* [ ] I have added relevent screenshots/images if necessary in a seperate folder.
* [ ] I have added my work in respective language folder.
* [ ] My changes generate no new warnings.

### :heart: Thank you!

2020-10-25 17:22 UTC, Mukulbaid63 commented
I have added README file in the next pull request because I forgot to add it in this one,Sorry for the inconvenience.

2020-10-26 09:30 UTC, yashaswibiyahut requested changes
Add readme file in this PR

2020-10-26 12:19 UTC, Mukulbaid63 commented
@yashaswibiyahut required changes have been committed.

2020-10-27 06:15 UTC, yashaswibiyahut commented
@Mukulbaid63 please add a running code

2020-10-27 14:30 UTC, yashaswibiyahut commented
kindly add a dynamic input and also add time and space complexity rest LGTM.

2020-10-27 15:31 UTC, Mukulbaid63 reviewed
Added Time complexity and Dynamic input feature

2020-10-28 06:27 UTC, yashaswibiyahut commented
![(Java) _ Online editor and compiler - Google Chrome 10_28_2020 11_55_51 AM (2)](https://user-images.githubusercontent.com/32020835/97400209-b6180580-1914-11eb-8da7-db66141af0b6.png)
**Add Running Code**. @Mukulbaid63

2020-10-28 07:27 UTC, Mukulbaid63 reviewed
Sorry for the inconvenience,added the missing code.Please review @yashaswibiyahut

2020-10-28 07:43 UTC, yashaswibiyahut requested changes
Rest LGTM

2020-10-28 07:43 UTC, yashaswibiyahut commented on Java/ChineseRemainderTheorem/CRT.java
> +                int n=sc.nextInt();
proper line alignment.

2020-10-28 10:21 UTC, Mukulbaid63 reviewed
Aligned. @yashaswibiyahut

2020-10-28 15:50 UTC, yashaswibiyahut approved these changes

2020-10-28 15:50 UTC, merged