python script for shapes
sanscript-tech/hacking-tools-scripts pull request #285
Opened 2020-11-06 19:38 UTC by NEEHITGOYAL

### Your checklist for this pull request
:warning: Please review the [guidelines for contributing](https://github.com/sanscript-tech/hacking-tools-scripts/blob/main/CONTRIBUTING.md) to this repository.

Parent issue: #("mention issue no.")
#213 
### Type of change

**Select all that applies**:
* [x] New feature (non-breaking change which adds functionality)
* [x] Bug fix (non-breaking change which fixes an issue)
* [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

### Checklist:

* [x] My code follows the style guidelines(Clean Code) of this project.
* [x] I have performed a self-review of my own code.
* [x] I have used consistent code conventions and clear function/method/variable names.
* [x] I have commented on my code, particularly in hard-to-understand areas.
* [x] I have created a helpful and easy to understand README.md which contains description, requirements and use case.
* [ ] I have added relevent screenshots/images if necessary in a seperate folder.
* [x] I have added my work in respective language folder.
* [x] My changes generate no new warnings.

### :heart: Thank you!

2020-11-07 11:41 UTC, tejan-singh requested changes

2020-11-07 11:41 UTC, tejan-singh commented on Python/shape-detection/Shape_Detection.py
> +    global shapes
error in line no. 22 please check again by running the script

2020-11-09 13:49 UTC, tejan-singh requested changes

2020-11-09 13:49 UTC, tejan-singh commented on Python/shape-detection/Shape_Detection.py
> +            shapes["Ellpise"].append(col)
Traceback (most recent call last):
  File "shape.py", line 174, in <module>
    shapes["Ellpise"].append(col)
KeyError: 'Ellpise'

I am getting this error in line no. 174

2020-11-09 17:26 UTC, NEEHITGOYAL commented
sir when i m running it wasn't giving any error but okk there was a variable mistake i resolved it kindly check it
![Screenshot (94)](https://user-images.githubusercontent.com/44130067/98575058-b930cf80-22de-11eb-9cf9-1d3b22f7e858.png)

2020-11-10 18:57 UTC, merged