Circle radius and center coordinates
sanscript-tech/hacking-tools-scripts pull request #340
Opened 2020-11-11 17:04 UTC by NEEHITGOYAL

### Your checklist for this pull request
:warning: Please review the [guidelines for contributing](https://github.com/sanscript-tech/hacking-tools-scripts/blob/main/CONTRIBUTING.md) to this repository.

Parent issue: #("mention issue no.")

### Type of change

**Select all that applies**:
* [x] New feature (non-breaking change which adds functionality)
* [x] Bug fix (non-breaking change which fixes an issue)
* [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [x] This change requires a documentation update

### Checklist:

* [x] My code follows the style guidelines(Clean Code) of this project.
* [x] I have performed a self-review of my own code.
* [x] I have used consistent code conventions and clear function/method/variable names.
* [x] I have commented on my code, particularly in hard-to-understand areas.
* [x] I have created a helpful and easy to understand README.md which contains description, requirements and use case.
* [x] I have added relevent screenshots/images if necessary in a seperate folder.
* [x] I have added my work in respective language folder.
* [x] My changes generate no new warnings.

### :heart: Thank you!

2020-11-11 19:11 UTC, yashaswibiyahut requested changes

2020-11-11 19:11 UTC, yashaswibiyahut commented on Python/circle_detection/README.md
> +
Add example or use case in readme file

2020-11-11 19:11 UTC, yashaswibiyahut commented on Python/circle_detection/circle.py
> +
add proper comments

2020-11-11 19:11 UTC, yashaswibiyahut commented
Squash the commits please

2020-11-12 06:28 UTC, NEEHITGOYAL commented
i have tried to rebase but i don't know what is happening actually i am squashing first time so i  searched 
and done it but here it is not showing anything

2020-11-12 12:23 UTC, tejan-singh commented
@NEEHITGOYAL if you are finding it difficult, then close this pull request and create a new one

2020-11-15 17:22 UTC, NEEHITGOYAL commented
i am opening new pr for same

2020-11-15 17:22 UTC, closed without merging