Password Strength Checker in C++
sanscript-tech/hacking-tools-scripts pull request #361
Opened 2020-11-13 13:21 UTC by japneetbhatia

### Your checklist for this pull request
:warning: Please review the [guidelines for contributing](https://github.com/sanscript-tech/hacking-tools-scripts/blob/main/CONTRIBUTING.md) to this repository.

Parent issue: #299

### Type of change

**Select all that applies**:
* [x] New feature (non-breaking change which adds functionality)
* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

### Checklist:

* [x] My code follows the style guidelines(Clean Code) of this project.
* [x] I have performed a self-review of my own code.
* [x] I have used consistent code conventions and clear function/method/variable names.
* [x] I have commented on my code, particularly in hard-to-understand areas.
* [x] I have created a helpful and easy to understand README.md which contains description, requirements and use case.
* [x] I have added relevent screenshots/images if necessary in a seperate folder.
* [x] I have added my work in respective language folder.
* [x] My changes generate no new warnings.

### :heart: Thank you!

2020-11-13 15:45 UTC, yashaswibiyahut requested changes

2020-11-13 15:45 UTC, yashaswibiyahut commented on C++/PasswordStrength/README.md
> +otherwise its Weak
Add sample use case or example

2020-11-13 15:45 UTC, yashaswibiyahut commented on C++/PasswordStrength/checkpassword.cpp
> +
Remove all extra spaces

2020-11-13 15:45 UTC, yashaswibiyahut commented on C++/PasswordStrength/checkpassword.cpp
> +void CheckPassword(string& input)
Add proper comments

2020-11-13 15:45 UTC, yashaswibiyahut commented on C++/PasswordStrength/README.md
> +
Add time and space complexity

2020-11-13 15:46 UTC, yashaswibiyahut commented
Please squash the commits

2020-11-17 08:45 UTC, tejan-singh commented
@japneetbhatia do not send a pull request from the main branch, Create another branch and send pr from that branch. Read contribution guidelines for more details.

2020-11-17 09:24 UTC, japneetbhatia commented
Ok @tejan-singh @yashaswibiyahut  I'll correct this by today

2020-11-20 06:17 UTC, closed without merging