PDF watermark added
sanscript-tech/hacking-tools-scripts pull request #394
Opened 2020-11-19 20:40 UTC by Mukulbaid63

### Your checklist for this pull request
:warning: Please review the [guidelines for contributing](https://github.com/sanscript-tech/hacking-tools-scripts/blob/main/CONTRIBUTING.md) to this repository.

Parent issue: #219 

### Type of change

**Select all that applies**:
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

### Checklist:

* [ ] My code follows the style guidelines(Clean Code) of this project.
* [ ] I have performed a self-review of my own code.
* [ ] I have used consistent code conventions and clear function/method/variable names.
* [ ] I have commented on my code, particularly in hard-to-understand areas.
* [ ] I have created a helpful and easy to understand README.md which contains description, requirements and use case.
* [ ] I have added relevent screenshots/images if necessary in a seperate folder.
* [ ] I have added my work in respective language folder.
* [ ] My changes generate no new warnings.

### :heart: Thank you!

2020-11-20 06:16 UTC, tejan-singh requested changes

2020-11-20 06:16 UTC, tejan-singh commented on Python/PDFWatermark/README.md
> +- This script built in Python is an Amazon Price Tracker.
Please check the document before sending PR.

2020-11-20 08:05 UTC, Mukulbaid63 commented
Apologies for that @tejan-singh

2020-11-20 15:33 UTC, Mukulbaid63 commented
@tejan-singh @SANKET7738

2020-11-20 18:58 UTC, tejan-singh requested changes
The generated pdf is corrupted. Please check your code again for correct working.

2020-11-20 19:01 UTC, tejan-singh requested changes

2020-11-20 19:01 UTC, tejan-singh commented on Python/PDFWatermark/README.md
> +    - The Original PDF Name.
Specify that the input pdf needs to be in the current location

2020-11-20 19:09 UTC, Mukulbaid63 commented
> The generated pdf is corrupted. Please check your code again for correct working.

It is working fine in my system and i have also got the output,should i share the image of the merged output pdf

2020-11-20 19:22 UTC, tejan-singh commented
You can add a sample pdf for testing purpose in your PR.

2020-11-20 20:23 UTC, Mukulbaid63 commented
> You can add a sample pdf for testing purpose in your PR.

You mean the output pdf which is watermarked?

2020-11-21 04:31 UTC, tejan-singh commented
You can to add an input pdf for testing

2020-11-21 15:22 UTC, Mukulbaid63 commented
Added.

2020-11-21 17:27 UTC, merged