Added script for detecting strenths of password
sanscript-tech/hacking-tools-scripts pull request #46
Opened 2020-10-19 10:10 UTC by Abhijeet-sonkar

fixes #41 
Added folder "Password_Checker"
folder contains :- 
-  the required python script
-  README.md   

Instruction about the script  is provided in the script.

2020-10-19 11:31 UTC, yashaswibiyahut commented
@Abhijeet-sonkar Please add an example/use case of how to use this script in the readme file.

2020-10-19 11:32 UTC, yashaswibiyahut requested changes
@Abhijeet-sonkar Please add an example/use case of how to use this script in the readme file.

2020-10-19 13:24 UTC, Abhijeet-sonkar commented
Added the screenshot of the python script
Please review my PR

2020-10-20 06:00 UTC, yashaswibiyahut approved these changes

2020-10-20 06:00 UTC, merged