BMI-Calculator-Added
sanscript-tech/hacking-tools-scripts pull request #84
Opened 2020-10-21 09:40 UTC by Ninjavin

I have added BMI Calculator in Python. Please review and suggest any necessary changes. Thank You. Issue Number #53

2020-10-21 11:14 UTC, yashaswibiyahut requested changes
Please add comments in your code.

2020-10-21 11:14 UTC, yashaswibiyahut commented on Python/BMICalculator/bmi-calculator.py
> +feet, inches = map(int, input(Fore.CYAN + "\nEnter height in feet and inches (example 5'3''): ")[:-2].split("'"))
@Ninjavin Instead of feet and inches Use: Enter your height? (inches or meters)  : 5.3
It will become more simple.

2020-10-22 10:09 UTC, Ninjavin commented
Hey @yashaswibiyahut I made the required changes. Please review. Thank you.

2020-10-22 15:46 UTC, yashaswibiyahut approved these changes

2020-10-22 15:46 UTC, merged